name: Docker Image CI/CD

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: activate buildkit in powershell
        run: |
          export DOCKER_BUILDKIT=1

      - name: Clone private RWCodeData repository
        run: |
          git clone git@github.com:vrg2121/RWCodeData.git /home/runner/work/rwcode_data

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile 
          platforms: linux/amd64 
          push: true
          tags: |
            ghcr.io/vrg2121/rwcode-ghcr:latest  
            ghcr.io/vrg2121/rwcode-ghcr:${{ github.sha }}  

      - name: Log out from GitHub Container Registry
        run: docker logout ghcr.io